### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by imomin** [OpenTalker/video-retalking#59]
I am running the code on Mac OSX Intel i7. I am getting below error.  Any idea what I am doing wrong? Do I need GPU card for this project.

```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cpu for inference.
[Step 0] Number of frames available for inference: 125
[Step 1] Landmarks Extraction in Video.
Traceback (most recent call last):
  File "/Users/user/Documents/projects/AI/DeepFake/video-retalking/inference.py", line 342, in <module>
    main()
  File "/Users/user/Documents/projects/AI/DeepFake/video-retalking/inference.py", line 78, in main
    kp_extractor = KeypointExtractor()
  File "/Users/user/Documents/projects/AI/DeepFake/video-retalking/third_part/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)   
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/face_alignment/api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 31, in __init__
    self.face_detector.to(device)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by revivebotai** [comment]
I am getting similar error. If you ever found the solution?

**Comment by HotWordland** [comment]
similar error too . use mac m1 chip

**Comment by aviadavi** [comment]
I get this too. any idea what can be done?

**Comment by supermurkote** [comment]
In my case, it worked for me.

You need to install ->

https://developer.nvidia.com/cuda-11-8-0-download-archive

and this one

conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia



-------------------------------------------------------

It didn't work with this one

conda install pytorch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 pytorch-cuda=12.1 -c pytorch -c nvidia
